# --- Required properties ---
# Unique key for the SonarQube project
sonar.projectKey=xx-sit-stackit-dev-exp:stackit-git-forgejo
# Project version
sonar.projectVersion=1.0

# --- Paths to source code and tests ---
# Path to the source code to be analyzed
sonar.sources=cmd,custom,docker,models,modules,options,packages,public,release-notes,releases,routers,services,templates,web_src
# Path to test files. These won't be analyzed for issues.
sonar.tests=tests
# Exclude test files from source code analysis
sonar.test.inclusions=**/*_test.go

# --- Coverage and Exclusions ---
# Path to the Go coverage report
sonar.go.coverage.reportPaths=coverage.out
# Exclude files and directories from analysis (e.g., vendor, node_modules)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/testdata/**,**/*.pb.go

# --- Other properties ---
# Encoding of the source files
sonar.sourceEncoding=UTF-8